sudo: required

services:
  - docker

env:
  global:
    - secure: "nuTeB44YPB406xgePUWXFvTP2dem6EuSA3jPowRjRzco/eVmfiLRsQpa8umPgwtrTAMZn7Qvn+kWiUikp+6KFMhvO1ycLNQpj9JOYIVnsfGbbdC2Q7gEVQuG0i7tqwHS+mef+NdZt/7rje04UUgzPU+48tKJDgQb/nosCdYgf7zjB3pRFAZ97OTyStOkMurQqwAKjNMSPDUA3mJsfrZ99SKwmAVLxbZ24ch39gzS0zF5kqMscxvQjM8wFZFpFQxIEZnkFuYOySWyaYGWxkZAJNNJij+iUJV3/b1A1ys4v5Zme/clWGooN24ndJAt+3KWLXJptXM/haEoI2JG0KYz0KWicivAX/27xTv6hi6KolNF8/dogbbwhmFDkqwevPai0eOTEA0JlIJuAuUjSlp+lpz8JUs5Z1OKeCAcbi9IFzxrOZ+MFoqVsLzyZJDjAzISx4Bt6GbtuNHUXFhbqFzSCOVQjuzaLkH+06snzAC7N8p6kVoRJeXNDqQ8qKbb+jlJamVn0fgRXXbfv6j76Un1/lq+XRx+NyT8WGWSPxh8/b+pS2U2hNenTwZaIlxNQ4BNfxiXyz3alB9bDbcXsrWEgJboXSzQQgcGYiq83k1C3vEIgSu7UqHVVt25O+5ScjqmJfDMEOkeRRqnXqw+30LBdvhaN1KUdwtMcg7VxzSmLkY="
    - secure: "KtP+z3il/wgoTZ8n2ehyQMcmYujSVe+mC8Vl7E7RsOw6c2bt5cRlZ/KT6pW5Xh/kWs3EPRP5fL4KTeKSZBEM1q2VgcLovB670qo6j1b3jqEgWj2tVEXCQQdGT9XNMl6JMMawfdi02OUEOG0RP6s6NF3m5vT6AkkNP9SY/JqqvOJbpqrwfTfVXRHEHi0DxAhEcOKE7pYW4arN6b0zBfG5mjZpU9qXsY1lNotuoHerKnbeL2ItuRB4TaMeBPte0pkUkawo83R38PKWDZgWBwmfY0DfkZNPNa4kvqyTzZS9SqTc8x0u3PFcmM40J9boiqJk+e7UCrNqT5R7KJ+ulq3AgS7FQiU9rvDFizAOKO4b5f3ENtvT2RJvux5p0zTxmLIJTSZxvKxVmR/RjOuRabpTRpsW3nPzV72lTyjcWx2FzIS4DzO5AR+DS023wMJ7JoPqSDyUqMX0xcCTqvgRU8UifgL5jPL6B7oEzFM/vb8Ir3XWoUAi7wdXwFYekV+8oF+KgjShuwcVrSsHK7yBKj6nuK3vS61A3FPG1qp8/UnTY5FcjSH5ah4shD/r93aep0JApJ7lyxClZovtepL9hXdXkE56wNRAMJ/qh4gcSF2H2qNhMNQSyW+h/eua3gh1lOiSc3uIGe+6VsdqexfRzu0br0x88zDyubrZan142rtBCWQ="
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=konfetti/homepage

script:
  - docker build -t $REPO .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
