sudo: required

services:
  - docker

env:
  global:
    - secure: "X+q0bvkhEOT2EbQtWjiovgaB1KQFNAlIHg4FnvFEcAFV0zcUZHhqTNwqIHP9nGk2mxEln5Zn4icZZ6M8JvTD/2HrTJbfWGCo45jJSk1QannpypnWLXwHwu9AbB9wHx3PpplxxJDxWOKXD+dRfIupxuN++iINTmfQnOWTTfmfxMScTChLTfgirdih9208n2Z7zpxCeDvVxbuDZnhFRYaPO0ekBUpeorllGy9IErLHb6aB9Lb/4QwD8r64FTJzTGb0NuzAJS+ewLTtld7RjHrDJFtV6bB8VEYJ0V1lCHrploiJD36QqUsMDQ6LJ7wet1oqru72sT5q+7eey9+liM5ieIMrXP8qWD+N9yFqLjc8Th0mqrXe/iPL3t+D0qZOOXTu7H03FGMRlOuSqcJ3SM0gXnSIZyda+nRJU5ZmxpCH19yjSQNDZOIVN7RIpwHzLHvlEBxiBadjRsTH6QvKfOro0lAN3WbMlk7pHqSS5mgQmJG7ie1KbSQVUoEhOwN0nY1Se3e6b4LO2kKHFBQppiREOj6Saffak7Z172qF+aadoJp19k2sF8WmMcp9U2KrTWAwQ6Azsyq+fFhXROSInTkzumQAqUb51Lk4qlp2msIReDcfB2c7nvdx/g1bN87n3pMk2LSSb7FZCh/kRk0yy3qg+kVO5EtehDO/pJd4UWWek5M="
    - secure: "KtP+z3il/wgoTZ8n2ehyQMcmYujSVe+mC8Vl7E7RsOw6c2bt5cRlZ/KT6pW5Xh/kWs3EPRP5fL4KTeKSZBEM1q2VgcLovB670qo6j1b3jqEgWj2tVEXCQQdGT9XNMl6JMMawfdi02OUEOG0RP6s6NF3m5vT6AkkNP9SY/JqqvOJbpqrwfTfVXRHEHi0DxAhEcOKE7pYW4arN6b0zBfG5mjZpU9qXsY1lNotuoHerKnbeL2ItuRB4TaMeBPte0pkUkawo83R38PKWDZgWBwmfY0DfkZNPNa4kvqyTzZS9SqTc8x0u3PFcmM40J9boiqJk+e7UCrNqT5R7KJ+ulq3AgS7FQiU9rvDFizAOKO4b5f3ENtvT2RJvux5p0zTxmLIJTSZxvKxVmR/RjOuRabpTRpsW3nPzV72lTyjcWx2FzIS4DzO5AR+DS023wMJ7JoPqSDyUqMX0xcCTqvgRU8UifgL5jPL6B7oEzFM/vb8Ir3XWoUAi7wdXwFYekV+8oF+KgjShuwcVrSsHK7yBKj6nuK3vS61A3FPG1qp8/UnTY5FcjSH5ah4shD/r93aep0JApJ7lyxClZovtepL9hXdXkE56wNRAMJ/qh4gcSF2H2qNhMNQSyW+h/eua3gh1lOiSc3uIGe+6VsdqexfRzu0br0x88zDyubrZan142rtBCWQ="
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=konfetti/homepage

script:
  - docker build -t $REPO .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
