sudo: required

services:
  - docker

env:
  global:
    - secure: "c5/xFTGktxG1025DeY2eyc9LMEBhFcAx2vfYGX1dJgCN2qlzT7reZCXVbDL/fhDUKQ9vKGMelSpkA/wEaRPP8NCJxBjOUbcf4xU9/j9tttq1IUePDovQKGPjFRrkvXJIz8dLsfyaKp3/SVM+1zSomIGXSHNNpHLpb82fXeZJGNhjBGwwrIsf4C5MQSQ+uz0J90aAaHkwryXMgxqUYnh8pEv5Rbz2SorAn0Xw3twwCyC40q7m8/R9s0IjAo63SVs0mwXdVG7l+3Ykm2xw1C61+4Dr0VSiPZuowasy3WeDR+wB7lJIw0KP4TsuvjuYDXhxzbKvF6u0WROgBUqU03fAxjh+JuPgqYvkIUhBdlTGz1A9n+a1/VSePbUps6HhYQrX9JfZNOrdF4vXNsiJpQn2Q2zIihIKQBME5mC0QmSzPkK3Eab8rQQaDUyRJggW9gr+gkBNcr9s5cSKMJpkPPADnXvz3mW7Z8CGzW2NJHV6kBBrD0n2/7JbxziVFGHvY9RJfaJLTEz6rSLnEkTIbqMraJpQuh++1RYhE1tfJ7cTokfHHdarXlYbf8cWBevczhn/3N/7DwyP0XR7C+kPRGW4Lc/aILoHKNjT8SHdTWYJX9tpOwDdAkpF8xKps3eydKE8mFlRzNWvhv9DOnjB7Vbttj/M/NQzAcTTqgiLTdZvdUA="
    - secure: "X+q0bvkhEOT2EbQtWjiovgaB1KQFNAlIHg4FnvFEcAFV0zcUZHhqTNwqIHP9nGk2mxEln5Zn4icZZ6M8JvTD/2HrTJbfWGCo45jJSk1QannpypnWLXwHwu9AbB9wHx3PpplxxJDxWOKXD+dRfIupxuN++iINTmfQnOWTTfmfxMScTChLTfgirdih9208n2Z7zpxCeDvVxbuDZnhFRYaPO0ekBUpeorllGy9IErLHb6aB9Lb/4QwD8r64FTJzTGb0NuzAJS+ewLTtld7RjHrDJFtV6bB8VEYJ0V1lCHrploiJD36QqUsMDQ6LJ7wet1oqru72sT5q+7eey9+liM5ieIMrXP8qWD+N9yFqLjc8Th0mqrXe/iPL3t+D0qZOOXTu7H03FGMRlOuSqcJ3SM0gXnSIZyda+nRJU5ZmxpCH19yjSQNDZOIVN7RIpwHzLHvlEBxiBadjRsTH6QvKfOro0lAN3WbMlk7pHqSS5mgQmJG7ie1KbSQVUoEhOwN0nY1Se3e6b4LO2kKHFBQppiREOj6Saffak7Z172qF+aadoJp19k2sF8WmMcp9U2KrTWAwQ6Azsyq+fFhXROSInTkzumQAqUb51Lk4qlp2msIReDcfB2c7nvdx/g1bN87n3pMk2LSSb7FZCh/kRk0yy3qg+kVO5EtehDO/pJd4UWWek5M="
    - secure: "ogt1ZsU4OnvnBI+awE8/rXj4fi2Mn6ZxuEUjnpM78R/qRMBj7OjP37DUC8zfHgqlmPZ7ZMUh5S5pWL2zNtwDsxOZhQcLRV1EHvTG/XE7jwXtuo35M7FbCipUvw35FKqIxiOSUVXBmXo9ZZcpPsNJSSJmnz7xNpjFOn+IIJGQv45sCD/zBLHinmRzVD7Fg+81TEPXE6DVn4gSrD0vP9MX8GoeJMdLu1oUmRrpdPwEs939MFOQ46Ay73vtfRYV9TC22zq1oSaBH7y0HvFo1f1TlOjERMIscrZxkJ18w0ZWPAHV4NWZ5shrQUtNuB9RlxEXoK6oWGf6V9tZJNZemoS1jlFCMErDRw50PnkrIkbAWUk8f+6sjn8DFvMjzcBMCpphKnccTfwJVMcYZgleqAC3K5nLC5DAwMTasjiSxJqLVMOHZk+rIZfZ/VvvjPS8c6iWjcTuS69U6eJx4K1sUzKmHwAj+VpiCYIaSlhKwiTrhjl2L1tZf/BYNOkH2o/QC4vslBqh4NPU/GwS4gPQT9mZY7I7DNyu3G5KoKMwmoHTde33MBECVT2RUAhZS924KWt4N/2COmHx8j6D32tWOCklLstY+Iltj3r1o9zphOVMOBfDhVTcMAa4Pxu2pQEWDLfC5qn1tXKdQFuK/eeqv/ro4xDOLGMcvHdliVwT33vJSvw="
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=konfetti/homepage

script:
  - docker build -t $REPO .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
